# Generated by Django 5.1.2 on 2024-11-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_user_administrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='administrador',
        ),
        migrations.AddField(
            model_name='usuarioentidad',
            name='administrador',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
