# Generated by Django 5.1.2 on 2024-12-26 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_user_administrador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaUnidad',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'usuario entidad',
                'verbose_name_plural': 'usuarios entidad',
            },
        ),
        migrations.AddField(
            model_name='usuarioentidad',
            name='area_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.areaunidad'),
        ),
        migrations.AddField(
            model_name='areaunidad',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.unidad'),
        ),
    ]
