# Generated by Django 5.1.2 on 2024-12-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_areaunidad_unidad_usuarioentidad_area_unidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name': 'unidad', 'verbose_name_plural': 'unidades'},
        ),
    ]
