# Generated by Django 5.1.2 on 2025-01-27 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_unidad_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('DIRECTOR_EJECUTIVO', 'DIRECTOR_EJECUTIVO'), ('SUBDIRECTOR', 'SUBDIRECTOR'), ('PROFESIONAL_ENCARGADO', 'PROFESIONAL_ENCARGADO'), ('TECNICO_PRESUPUESTO', 'TECNICO_PRESUPUESTO')], max_length=100)),
                ('crear_usuarios', models.BooleanField(default=False)),
                ('crear_cdps', models.BooleanField(default=False)),
                ('crear_presupuesto', models.BooleanField(default=False)),
                ('crear_proyeccion', models.BooleanField(default=False)),
                ('consultas', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuarioentidad',
            name='rol_sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.rol'),
        ),
    ]
