# Generated by Django 5.1.2 on 2025-01-29 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0002_direccion_remove_registerprofesor_comuna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerprofesor',
            name='direccion',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='profesores.direccion'),
        ),
    ]
