# Generated by Django 5.1.2 on 2025-01-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0004_alter_registerprofesor_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerprofesor',
            name='fecha_nacimiento',
            field=models.CharField(max_length=20),
        ),
    ]
