# Generated by Django 5.1.2 on 2025-01-29 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0005_alter_registerprofesor_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerprofesor',
            name='direccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profesores.direccion'),
        ),
        migrations.AlterField(
            model_name='registerprofesor',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
