# Generated by Django 5.1.2 on 2025-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0006_alter_registerprofesor_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='comuna',
            field=models.CharField(choices=[('', 'Seleccione una comuna')], max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(default='Chile', max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='region',
            field=models.CharField(choices=[('', 'Seleccione una región')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registerprofesor',
            name='nacionalidad',
            field=models.CharField(default='Chilena', max_length=100),
        ),
    ]
