# Generated by Django 5.1.2 on 2025-01-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0007_alter_direccion_comuna_alter_direccion_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerprofesor',
            name='cv',
            field=models.FileField(default='-', upload_to='cv_profesores/'),
        ),
        migrations.AlterField(
            model_name='registerprofesor',
            name='foto',
            field=models.FileField(default='-', upload_to='fotos_profesores/'),
        ),
    ]
