# Generated by Django 5.1.2 on 2025-01-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0009_alter_registerprofesor_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerprofesor',
            name='telefono',
            field=models.CharField(max_length=9, verbose_name='Teléfono: 9 1234 5678'),
        ),
    ]
