# Generated by Django 5.1.2 on 2025-01-30 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0012_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerprofesor',
            name='fecha_nacimiento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profesores.fechanacimiento'),
        ),
    ]
