# Generated by Django 5.1.2 on 2025-01-30 18:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0015_alter_fechanacimiento_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='comuna',
            field=models.CharField(choices=[('Arica', 'Arica'), ('Camarones', 'Camarones'), ('Putre', 'Putre'), ('General Lagos', 'General Lagos'), ('Iquique', 'Iquique'), ('Alto Hospicio', 'Alto Hospicio'), ('Pozo Almonte', 'Pozo Almonte'), ('Camiña', 'Camiña'), ('Colchane', 'Colchane'), ('Huara', 'Huara'), ('Pica', 'Pica'), ('Antofagasta', 'Antofagasta'), ('Mejillones', 'Mejillones'), ('Sierra Gorda', 'Sierra Gorda'), ('Taltal', 'Taltal'), ('Calama', 'Calama'), ('Ollagüe', 'Ollagüe'), ('San Pedro de Atacama', 'San Pedro de Atacama'), ('Tocopilla', 'Tocopilla'), ('María Elena', 'María Elena'), ('Copiapó', 'Copiapó'), ('Caldera', 'Caldera'), ('Tierra Amarilla', 'Tierra Amarilla'), ('Chañaral', 'Chañaral'), ('Diego de Almagro', 'Diego de Almagro'), ('Vallenar', 'Vallenar'), ('Alto del Carmen', 'Alto del Carmen'), ('Freirina', 'Freirina'), ('Huasco', 'Huasco'), ('La Serena', 'La Serena'), ('Coquimbo', 'Coquimbo'), ('Andacollo', 'Andacollo'), ('La Higuera', 'La Higuera'), ('Paiguano', 'Paiguano'), ('Vicuña', 'Vicuña'), ('Illapel', 'Illapel'), ('Canela', 'Canela'), ('Los Vilos', 'Los Vilos'), ('Salamanca', 'Salamanca'), ('Ovalle', 'Ovalle'), ('Combarbalá', 'Combarbalá'), ('Monte Patria', 'Monte Patria'), ('Punitaqui', 'Punitaqui'), ('Río Hurtado', 'Río Hurtado'), ('Valparaíso', 'Valparaíso'), ('Casablanca', 'Casablanca'), ('Concón', 'Concón'), ('Juan Fernández', 'Juan Fernández'), ('Puchuncaví', 'Puchuncaví'), ('Quintero', 'Quintero'), ('Viña del Mar', 'Viña del Mar'), ('Isla de Pascua', 'Isla de Pascua'), ('Los Andes', 'Los Andes'), ('Calle Larga', 'Calle Larga'), ('Rinconada', 'Rinconada'), ('San Esteban', 'San Esteban'), ('La Ligua', 'La Ligua'), ('Cabildo', 'Cabildo'), ('Papudo', 'Papudo'), ('Petorca', 'Petorca'), ('Zapallar', 'Zapallar'), ('Quillota', 'Quillota'), ('Calera', 'Calera'), ('Hijuelas', 'Hijuelas'), ('La Cruz', 'La Cruz'), ('Nogales', 'Nogales'), ('San Antonio', 'San Antonio'), ('Algarrobo', 'Algarrobo'), ('Cartagena', 'Cartagena'), ('El Quisco', 'El Quisco'), ('El Tabo', 'El Tabo'), ('Santo Domingo', 'Santo Domingo'), ('San Felipe', 'San Felipe'), ('Catemu', 'Catemu'), ('Llaillay', 'Llaillay'), ('Panquehue', 'Panquehue'), ('Putaendo', 'Putaendo'), ('Santa María', 'Santa María'), ('Quilpué', 'Quilpué'), ('Limache', 'Limache'), ('Olmué', 'Olmué'), ('Villa Alemana', 'Villa Alemana'), ('Rancagua', 'Rancagua'), ('Codegua', 'Codegua'), ('Coinco', 'Coinco'), ('Coltauco', 'Coltauco'), ('Doñihue', 'Doñihue'), ('Graneros', 'Graneros'), ('Las Cabras', 'Las Cabras'), ('Machalí', 'Machalí'), ('Malloa', 'Malloa'), ('Mostazal', 'Mostazal'), ('Olivar', 'Olivar'), ('Peumo', 'Peumo'), ('Pichidegua', 'Pichidegua'), ('Quinta de Tilcoco', 'Quinta de Tilcoco'), ('Rengo', 'Rengo'), ('Requínoa', 'Requínoa'), ('San Vicente', 'San Vicente'), ('Pichilemu', 'Pichilemu'), ('La Estrella', 'La Estrella'), ('Litueche', 'Litueche'), ('Marchihue', 'Marchihue'), ('Navidad', 'Navidad'), ('Paredones', 'Paredones'), ('San Fernando', 'San Fernando'), ('Chépica', 'Chépica'), ('Chimbarongo', 'Chimbarongo'), ('Lolol', 'Lolol'), ('Nancagua', 'Nancagua'), ('Palmilla', 'Palmilla'), ('Peralillo', 'Peralillo'), ('Placilla', 'Placilla'), ('Pumanque', 'Pumanque'), ('Santa Cruz', 'Santa Cruz'), ('Talca', 'Talca'), ('Constitución', 'Constitución'), ('Curepto', 'Curepto'), ('Empedrado', 'Empedrado'), ('Maule', 'Maule'), ('Pelarco', 'Pelarco'), ('Pencahue', 'Pencahue'), ('Río Claro', 'Río Claro'), ('San Clemente', 'San Clemente'), ('San Rafael', 'San Rafael'), ('Cauquenes', 'Cauquenes'), ('Chanco', 'Chanco'), ('Pelluhue', 'Pelluhue'), ('Curicó', 'Curicó'), ('Hualañé', 'Hualañé'), ('Licantén', 'Licantén'), ('Molina', 'Molina'), ('Rauco', 'Rauco'), ('Romeral', 'Romeral'), ('Sagrada Familia', 'Sagrada Familia'), ('Teno', 'Teno'), ('Vichuquén', 'Vichuquén'), ('Linares', 'Linares'), ('Colbún', 'Colbún'), ('Longaví', 'Longaví'), ('Parral', 'Parral'), ('Retiro', 'Retiro'), ('San Javier', 'San Javier'), ('Villa Alegre', 'Villa Alegre'), ('Yerbas Buenas', 'Yerbas Buenas'), ('Cobquecura', 'Cobquecura'), ('Coelemu', 'Coelemu'), ('Ninhue', 'Ninhue'), ('Portezuelo', 'Portezuelo'), ('Quirihue', 'Quirihue'), ('Ránquil', 'Ránquil'), ('Treguaco', 'Treguaco'), ('Bulnes', 'Bulnes'), ('Chillán Viejo', 'Chillán Viejo'), ('Chillán', 'Chillán'), ('El Carmen', 'El Carmen'), ('Pemuco', 'Pemuco'), ('Pinto', 'Pinto'), ('Quillón', 'Quillón'), ('San Ignacio', 'San Ignacio'), ('Yungay', 'Yungay'), ('Coihueco', 'Coihueco'), ('Ñiquén', 'Ñiquén'), ('San Carlos', 'San Carlos'), ('San Fabián', 'San Fabián'), ('San Nicolás', 'San Nicolás'), ('Concepción', 'Concepción'), ('Coronel', 'Coronel'), ('Chiguayante', 'Chiguayante'), ('Florida', 'Florida'), ('Hualqui', 'Hualqui'), ('Lota', 'Lota'), ('Penco', 'Penco'), ('San Pedro de la Paz', 'San Pedro de la Paz'), ('Santa Juana', 'Santa Juana'), ('Talcahuano', 'Talcahuano'), ('Tomé', 'Tomé'), ('Hualpén', 'Hualpén'), ('Lebu', 'Lebu'), ('Arauco', 'Arauco'), ('Cañete', 'Cañete'), ('Contulmo', 'Contulmo'), ('Curanilahue', 'Curanilahue'), ('Los Álamos', 'Los Álamos'), ('Tirúa', 'Tirúa'), ('Los Ángeles', 'Los Ángeles'), ('Antuco', 'Antuco'), ('Cabrero', 'Cabrero'), ('Laja', 'Laja'), ('Mulchén', 'Mulchén'), ('Nacimiento', 'Nacimiento'), ('Negrete', 'Negrete'), ('Quilaco', 'Quilaco'), ('Quilleco', 'Quilleco'), ('San Rosendo', 'San Rosendo'), ('Santa Bárbara', 'Santa Bárbara'), ('Tucapel', 'Tucapel'), ('Yumbel', 'Yumbel'), ('Alto Biobío', 'Alto Biobío'), ('Temuco', 'Temuco'), ('Carahue', 'Carahue'), ('Cunco', 'Cunco'), ('Curarrehue', 'Curarrehue'), ('Freire', 'Freire'), ('Galvarino', 'Galvarino'), ('Gorbea', 'Gorbea'), ('Lautaro', 'Lautaro'), ('Loncoche', 'Loncoche'), ('Melipeuco', 'Melipeuco'), ('Nueva Imperial', 'Nueva Imperial'), ('Padre las Casas', 'Padre las Casas'), ('Perquenco', 'Perquenco'), ('Pitrufquén', 'Pitrufquén'), ('Pucón', 'Pucón'), ('Saavedra', 'Saavedra'), ('Teodoro Schmidt', 'Teodoro Schmidt'), ('Toltén', 'Toltén'), ('Vilcún', 'Vilcún'), ('Villarrica', 'Villarrica'), ('Cholchol', 'Cholchol'), ('Angol', 'Angol'), ('Collipulli', 'Collipulli'), ('Curacautín', 'Curacautín'), ('Ercilla', 'Ercilla'), ('Lonquimay', 'Lonquimay'), ('Los Sauces', 'Los Sauces'), ('Lumaco', 'Lumaco'), ('Purén', 'Purén'), ('Renaico', 'Renaico'), ('Traiguén', 'Traiguén'), ('Victoria', 'Victoria'), ('Valdivia', 'Valdivia'), ('Corral', 'Corral'), ('Lanco', 'Lanco'), ('Los Lagos', 'Los Lagos'), ('Máfil', 'Máfil'), ('Mariquina', 'Mariquina'), ('Paillaco', 'Paillaco'), ('Panguipulli', 'Panguipulli'), ('La Unión', 'La Unión'), ('Futrono', 'Futrono'), ('Lago Ranco', 'Lago Ranco'), ('Río Bueno', 'Río Bueno'), ('Puerto Montt', 'Puerto Montt'), ('Calbuco', 'Calbuco'), ('Cochamó', 'Cochamó'), ('Fresia', 'Fresia'), ('Frutillar', 'Frutillar'), ('Los Muermos', 'Los Muermos'), ('Llanquihue', 'Llanquihue'), ('Maullín', 'Maullín'), ('Puerto Varas', 'Puerto Varas'), ('Castro', 'Castro'), ('Ancud', 'Ancud'), ('Chonchi', 'Chonchi'), ('Curaco de Vélez', 'Curaco de Vélez'), ('Dalcahue', 'Dalcahue'), ('Puqueldón', 'Puqueldón'), ('Queilén', 'Queilén'), ('Quellón', 'Quellón'), ('Quemchi', 'Quemchi'), ('Quinchao', 'Quinchao'), ('Osorno', 'Osorno'), ('Puerto Octay', 'Puerto Octay'), ('Purranque', 'Purranque'), ('Puyehue', 'Puyehue'), ('Río Negro', 'Río Negro'), ('San Juan de la Costa', 'San Juan de la Costa'), ('San Pablo', 'San Pablo'), ('Chaitén', 'Chaitén'), ('Futaleufú', 'Futaleufú'), ('Hualaihué', 'Hualaihué'), ('Palena', 'Palena'), ('Coihaique', 'Coihaique'), ('Lago Verde', 'Lago Verde'), ('Aisén', 'Aisén'), ('Cisnes', 'Cisnes'), ('Guaitecas', 'Guaitecas'), ('Cochrane', 'Cochrane'), ('O’Higgins', 'O’Higgins'), ('Tortel', 'Tortel'), ('Chile Chico', 'Chile Chico'), ('Río Ibáñez', 'Río Ibáñez'), ('Punta Arenas', 'Punta Arenas'), ('Laguna Blanca', 'Laguna Blanca'), ('Río Verde', 'Río Verde'), ('San Gregorio', 'San Gregorio'), ('Cabo de Hornos (Ex Navarino)', 'Cabo de Hornos (Ex Navarino)'), ('Antártica', 'Antártica'), ('Porvenir', 'Porvenir'), ('Primavera', 'Primavera'), ('Timaukel', 'Timaukel'), ('Natales', 'Natales'), ('Torres del Paine', 'Torres del Paine'), ('Cerrillos', 'Cerrillos'), ('Cerro Navia', 'Cerro Navia'), ('Conchalí', 'Conchalí'), ('El Bosque', 'El Bosque'), ('Estación Central', 'Estación Central'), ('Huechuraba', 'Huechuraba'), ('Independencia', 'Independencia'), ('La Cisterna', 'La Cisterna'), ('La Florida', 'La Florida'), ('La Granja', 'La Granja'), ('La Pintana', 'La Pintana'), ('La Reina', 'La Reina'), ('Las Condes', 'Las Condes'), ('Lo Barnechea', 'Lo Barnechea'), ('Lo Espejo', 'Lo Espejo'), ('Lo Prado', 'Lo Prado'), ('Macul', 'Macul'), ('Maipú', 'Maipú'), ('Ñuñoa', 'Ñuñoa'), ('Pedro Aguirre Cerda', 'Pedro Aguirre Cerda'), ('Peñalolén', 'Peñalolén'), ('Providencia', 'Providencia'), ('Pudahuel', 'Pudahuel'), ('Quilicura', 'Quilicura'), ('Quinta Normal', 'Quinta Normal'), ('Recoleta', 'Recoleta'), ('Renca', 'Renca'), ('Santiago', 'Santiago'), ('San Joaquín', 'San Joaquín'), ('San Miguel', 'San Miguel'), ('San Ramón', 'San Ramón'), ('Vitacura', 'Vitacura'), ('Puente Alto', 'Puente Alto'), ('Pirque', 'Pirque'), ('San José de Maipo', 'San José de Maipo'), ('Colina', 'Colina'), ('Lampa', 'Lampa'), ('Tiltil', 'Tiltil'), ('San Bernardo', 'San Bernardo'), ('Buin', 'Buin'), ('Calera de Tango', 'Calera de Tango'), ('Paine', 'Paine'), ('Melipilla', 'Melipilla'), ('Alhué', 'Alhué'), ('Curacaví', 'Curacaví'), ('María Pinto', 'María Pinto'), ('San Pedro', 'San Pedro'), ('Talagante', 'Talagante'), ('El Monte', 'El Monte'), ('Isla de Maipo', 'Isla de Maipo'), ('Padre Hurtado', 'Padre Hurtado'), ('Peñaflor', 'Peñaflor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(blank=True, default='Chile', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='region',
            field=models.CharField(blank=True, choices=[('Arica y Parinacota', 'Arica y Parinacota'), ('Tarapacá', 'Tarapacá'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaíso', 'Valparaíso'), ('Región del Libertador Gral. Bernardo O’Higgins', 'Región del Libertador Gral. Bernardo O’Higgins'), ('Región del Maule', 'Región del Maule'), ('Región de Ñuble', 'Región de Ñuble'), ('Región del Biobío', 'Región del Biobío'), ('Región de la Araucanía', 'Región de la Araucanía'), ('Región de Los Ríos', 'Región de Los Ríos'), ('Región de Los Lagos', 'Región de Los Lagos'), ('Región Aisén del Gral. Carlos Ibáñez del Campo', 'Región Aisén del Gral. Carlos Ibáñez del Campo'), ('Región de Magallanes y de la Antártica Chilena', 'Región de Magallanes y de la Antártica Chilena'), ('Región Metropolitana de Santiago', 'Región Metropolitana de Santiago')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fechanacimiento',
            name='day',
            field=models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=2, null=True, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='fechanacimiento',
            name='month',
            field=models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, null=True, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='fechanacimiento',
            name='year',
            field=models.CharField(choices=[('1930', '1930'), ('1931', '1931'), ('1932', '1932'), ('1933', '1933'), ('1934', '1934'), ('1935', '1935'), ('1936', '1936'), ('1937', '1937'), ('1938', '1938'), ('1939', '1939'), ('1940', '1940'), ('1941', '1941'), ('1942', '1942'), ('1943', '1943'), ('1944', '1944'), ('1945', '1945'), ('1946', '1946'), ('1947', '1947'), ('1948', '1948'), ('1949', '1949'), ('1950', '1950'), ('1951', '1951'), ('1952', '1952'), ('1953', '1953'), ('1954', '1954'), ('1955', '1955'), ('1956', '1956'), ('1957', '1957'), ('1958', '1958'), ('1959', '1959'), ('1960', '1960'), ('1961', '1961'), ('1962', '1962'), ('1963', '1963'), ('1964', '1964'), ('1965', '1965'), ('1966', '1966'), ('1967', '1967'), ('1968', '1968'), ('1969', '1969'), ('1970', '1970'), ('1971', '1971'), ('1972', '1972'), ('1973', '1973'), ('1974', '1974'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=4, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='registerprofesor',
            name='apellidos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registerprofesor',
            name='cv',
            field=models.FileField(null=True, upload_to='cv_profesores/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='registerprofesor',
            name='direccion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profesores.direccion'),
        ),
        migrations.AlterField(
            model_name='registerprofesor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registerprofesor',
            name='fecha_nacimiento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profesores.fechanacimiento'),
        ),
        migrations.AlterField(
            model_name='registerprofesor',
            name='foto',
            field=models.FileField(null=True, upload_to='fotos_profesores/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='registerprofesor',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registerprofesor',
            name='rut',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='registerprofesor',
            name='sexo',
            field=models.CharField(choices=[('', 'Seleccione un sexo'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Prefiero no decir', 'Prefiero no decir')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registerprofesor',
            name='telefono',
            field=models.CharField(max_length=11, null=True, verbose_name='Teléfono'),
        ),
    ]
