# Generated by Django 5.1.2 on 2025-01-31 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0017_alter_direccion_comuna_alter_direccion_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherUser',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=10)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
