# Generated by Django 5.1.2 on 2025-01-31 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0018_teacheruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerprofesor',
            name='rut',
        ),
        migrations.AddField(
            model_name='registerprofesor',
            name='TeacherUser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profesores.teacheruser'),
        ),
    ]
