# Generated by Django 5.1.2 on 2025-01-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0019_remove_registerprofesor_rut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerprofesor',
            old_name='TeacherUser',
            new_name='teacher_user',
        ),
    ]
