# Generated by Django 5.1.2 on 2024-12-30 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0002_cdp_item_alter_cdp_fecha_cdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdp',
            name='Item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cdp.itempresupuestario'),
        ),
    ]
