# Generated by Django 5.1.2 on 2024-12-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0004_cdpcounter_remove_cdp_cuenta_contable_alter_cdp_cdp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdp',
            old_name='Item',
            new_name='ItemPresupuestario',
        ),
        migrations.RemoveField(
            model_name='cdp',
            name='programa',
        ),
        migrations.AlterField(
            model_name='cdp',
            name='fondo',
            field=models.CharField(choices=[('SEP', 'SEP'), ('NORMAL/REGULAR', 'NORMAL/REGULAR'), ('PIE', 'PIE'), ('JUNJI', 'JUNJI'), ('PRO-RETENCION', 'PRO-RETENCION'), ('MANTENIMIENTO', 'MANTENIMIENTO'), ('APORTE FISCAL', 'APORTE FISCAL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cdp',
            name='otros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
