# Generated by Django 5.1.2 on 2025-01-02 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0005_rename_item_cdp_itempresupuestario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='year',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=2021)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cdp',
            name='ItemPresupuestario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cdps', to='cdp.itempresupuestario'),
        ),
        migrations.AlterField(
            model_name='subtitulopresupuestario',
            name='programa_presupuestario',
            field=models.CharField(choices=[('P01 GASTOS ADMINISTRATIVOS', 'P01 GASTOS ADMINISTRATIVOS'), ('P02 SERVICIOS EDUCATIVOS', 'P02 SERVICIOS EDUCATIVOS')], max_length=50),
        ),
    ]
