# Generated by Django 5.1.2 on 2025-01-02 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0006_year_alter_cdp_itempresupuestario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('id_relacion', models.CharField(max_length=36)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
