# Generated by Django 5.1.2 on 2025-01-02 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0007_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='pdf',
            new_name='pdf_programa_presupuestario',
        ),
        migrations.AddField(
            model_name='subtitulopresupuestario',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitulos_presupuestarios', to='cdp.year'),
        ),
    ]
