# Generated by Django 5.1.2 on 2025-01-08 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0009_rename_itempresupuestario_cdp_item_presupuestario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdp',
            old_name='documento',
            new_name='n_orden',
        ),
        migrations.AlterField(
            model_name='cdp',
            name='fondo',
            field=models.CharField(choices=[('SEP', 'SEP'), ('NORMAL/REGULAR', 'NORMAL/REGULAR'), ('PIE', 'PIE'), ('JUNJI', 'JUNJI'), ('PRO-RETENCION', 'PRO-RETENCION'), ('MANTENIMIENTO', 'MANTENIMIENTO'), ('APORTE FISCAL', 'APORTE FISCAL'), ('OTROS', 'OTROS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cdp',
            name='item_presupuestario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='cdps', to='cdp.itempresupuestario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cdpcounter',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
