# Generated by Django 5.1.2 on 2025-01-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0010_rename_documento_cdp_n_orden_alter_cdp_fondo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdp',
            name='item_presupuestario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdps', to='cdp.itempresupuestario'),
        ),
    ]
