# Generated by Django 5.1.2 on 2025-01-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0011_alter_cdp_item_presupuestario'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempresupuestario',
            name='ejecucion_presupuestaria_item',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cdpcounter',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
