# Generated by Django 5.1.2 on 2025-01-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0012_itempresupuestario_ejecucion_presupuestaria_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempresupuestario',
            old_name='ejecucion_presupuestaria_item',
            new_name='ajuste_presupuestaria_item',
        ),
    ]
