# Generated by Django 5.1.2 on 2025-01-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0013_rename_ejecucion_presupuestaria_item_itempresupuestario_ajuste_presupuestaria_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempresupuestario',
            old_name='ajuste_presupuestaria_item',
            new_name='ajuste_presupuestario_item',
        ),
    ]
