# Generated by Django 5.1.2 on 2025-01-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0014_rename_ajuste_presupuestaria_item_itempresupuestario_ajuste_presupuestario_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdp',
            name='year_presupuestario',
            field=models.IntegerField(default=2025),
        ),
    ]
