# Generated by Django 5.1.2 on 2025-01-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0015_cdp_year_presupuestario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdp',
            options={'verbose_name': 'CDP', 'verbose_name_plural': 'Listados cdepes'},
        ),
        migrations.AddField(
            model_name='cdp',
            name='estado',
            field=models.CharField(choices=[('ingresado', 'ingresado'), ('refrendado', 'refrendado'), ('rechazado', 'rechazado')], default='ingresado', max_length=20),
        ),
        migrations.AlterField(
            model_name='cdp',
            name='folio_sigfe',
            field=models.CharField(default='Por definir', max_length=11),
        ),
        migrations.AlterField(
            model_name='cdp',
            name='n_orden',
            field=models.CharField(default='Por definir', max_length=50),
        ),
        migrations.AlterField(
            model_name='cdp',
            name='numero_requerimiento',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cdp',
            name='otros',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
