# Generated by Django 5.1.2 on 2025-01-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0016_alter_cdp_options_cdp_estado_alter_cdp_folio_sigfe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdp',
            options={},
        ),
        migrations.RemoveField(
            model_name='cdp',
            name='year_presupuestario',
        ),
    ]
