# Generated by Django 5.1.2 on 2025-01-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0017_alter_cdp_options_remove_cdp_year_presupuestario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdp',
            name='year_presupuestario',
            field=models.IntegerField(default=2025),
        ),
    ]
