# Generated by Django 5.1.2 on 2025-01-21 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0018_cdp_year_presupuestario'),
        ('establecimiento', '0044_remove_tituloitemdiagnostico_orden_and_more'),
        ('usuario', '0005_alter_unidad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdp',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdps', to='establecimiento.establecimiento'),
        ),
        migrations.AlterField(
            model_name='cdp',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cdps', to='usuario.unidad'),
        ),
        migrations.CreateModel(
            name='ProyeccionAnual',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.establecimiento')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdp.year')),
            ],
        ),
        migrations.CreateModel(
            name='Subvencion',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('fondo', models.CharField(choices=[('SEP', 'SEP'), ('NORMAL/REGULAR', 'NORMAL/REGULAR'), ('PIE', 'PIE'), ('JUNJI', 'JUNJI'), ('PRO-RETENCION', 'PRO-RETENCION'), ('MANTENIMIENTO', 'MANTENIMIENTO'), ('APORTE FISCAL', 'APORTE FISCAL'), ('OTROS', 'OTROS')], max_length=20)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('proyeccion_anual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdp.proyeccionanual')),
            ],
        ),
        migrations.CreateModel(
            name='MesProyectado',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('estado', models.CharField(choices=[('es', 'Estimado'), ('re', 'Real')], max_length=20)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subvencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdp.subvencion')),
            ],
        ),
    ]
