# Generated by Django 5.1.2 on 2025-01-21 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0019_alter_cdp_establecimiento_alter_cdp_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesproyectado',
            name='subvencion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='meses_proyectados', to='cdp.subvencion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyeccionanual',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones', to='cdp.year'),
        ),
        migrations.AlterField(
            model_name='subvencion',
            name='proyeccion_anual',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='subvenciones', to='cdp.proyeccionanual'),
            preserve_default=False,
        ),
    ]
