# Generated by Django 5.1.2 on 2025-01-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0020_alter_mesproyectado_subvencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyeccionanual',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyeccion', to='cdp.year'),
        ),
    ]
