# Generated by Django 5.1.2 on 2025-01-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp', '0022_alter_proyeccionanual_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesproyectado',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'INGRESO'), ('REMUNERACIONES', 'REMUNERACIONES')], default='INGRESO', max_length=20),
        ),
        migrations.AlterField(
            model_name='mesproyectado',
            name='estado',
            field=models.CharField(choices=[('Estimado', 'Estimado'), ('Real', 'Real')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mesproyectado',
            name='mes',
            field=models.CharField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], max_length=20),
        ),
    ]
