# Generated by Django 5.1.2 on 2024-11-07 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimiento', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominaprecios',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.entidad'),
        ),
        migrations.AddField(
            model_name='categoriapartidas',
            name='nomina_precios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.nominaprecios'),
        ),
        migrations.AddField(
            model_name='partidanomina',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.categoriapartidas'),
        ),
        migrations.AddField(
            model_name='partidanomina',
            name='nomina_precios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.nominaprecios'),
        ),
    ]
