# Generated by Django 5.1.2 on 2024-11-07 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimiento', '0001_initial'),
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='partida_nomina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Partida_mantencion', to='mantenimiento.partidanomina'),
        ),
        migrations.AddField(
            model_name='item_partida',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.partida'),
        ),
        migrations.AddField(
            model_name='recinto',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='establecimiento.estadorecinto'),
        ),
        migrations.AddField(
            model_name='recinto',
            name='pabellon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.pabellon'),
        ),
        migrations.AddField(
            model_name='recinto_partida',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.partida'),
        ),
        migrations.AddField(
            model_name='recinto_partida',
            name='recinto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.recinto'),
        ),
        migrations.AddField(
            model_name='tiporecinto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='establecimiento.categoriarecinto'),
        ),
        migrations.AddField(
            model_name='recinto',
            name='tipo_recinto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimiento.tiporecinto'),
        ),
        migrations.AddField(
            model_name='tiporecinto_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.item'),
        ),
        migrations.AddField(
            model_name='tiporecinto_item',
            name='tipo_recinto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.tiporecinto'),
        ),
    ]
