# Generated by Django 5.1.2 on 2024-11-09 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0004_planinfraestructura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadorecinto',
            options={'verbose_name': 'Estado Recinto', 'verbose_name_plural': 'Estados Recinto'},
        ),
        migrations.AddField(
            model_name='recinto_partida',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimiento.planinfraestructura'),
        ),
    ]
