# Generated by Django 5.1.2 on 2024-11-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0005_alter_estadorecinto_options_recinto_partida_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recinto_partida',
            name='total',
        ),
    ]
