# Generated by Django 5.1.2 on 2024-11-09 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0006_remove_recinto_partida_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='recinto_partida',
            name='item_partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimiento.item'),
        ),
    ]
