# Generated by Django 5.1.2 on 2024-11-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0007_recinto_partida_item_partida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recinto_partida',
            old_name='item_partida',
            new_name='item',
        ),
    ]
