# Generated by Django 5.1.2 on 2024-11-10 01:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0010_alter_tiporecinto_categoria_instalaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recinto_CategoriaInstalaciones',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('estado', models.IntegerField(choices=[(1, 'Sin Evaluar'), (2, 'Buen Funcionamiento'), (3, 'Fallas Leves'), (4, 'Necesita Pronta Revisión'), (5, 'No Funciona'), (6, 'No es posible evaluar estado'), (7, 'No exite ese tipo de instalación')], default=1)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('categoria_instalaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.categoriainstalaciones')),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.recinto')),
            ],
            options={
                'verbose_name': 'Instalación Recinto Pabellon',
                'verbose_name_plural': 'Instalaciones Recinto Pabellones',
            },
        ),
    ]
