# Generated by Django 5.1.2 on 2024-11-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0011_recinto_categoriainstalaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoInstalaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=36)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado Instalaciones',
                'verbose_name_plural': 'Estados Instalaciones',
            },
        ),
        migrations.AlterField(
            model_name='recinto_categoriainstalaciones',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'Sin Evaluar'), (2, 'Buen Funcionamiento'), (3, 'Fallas Leves'), (4, 'Necesita Pronta Revisión'), (5, 'No Funciona'), (6, 'No es posible evaluar estado'), (7, 'No exite ese tipo de instalación')], default=1, null=True),
        ),
    ]
