# Generated by Django 5.1.2 on 2024-11-10 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0013_remove_recinto_categoriainstalaciones_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recinto_categoriainstalaciones',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='establecimiento.estadoinstalaciones'),
        ),
    ]
