# Generated by Django 5.1.2 on 2024-11-10 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0014_recinto_categoriainstalaciones_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recinto_categoriainstalaciones',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimiento.planinfraestructura'),
        ),
    ]
