# Generated by Django 5.1.2 on 2024-11-10 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0015_recinto_categoriainstalaciones_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recinto_categoriainstalaciones',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.estadoinstalaciones'),
        ),
    ]
