# Generated by Django 5.1.2 on 2024-11-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0016_alter_recinto_categoriainstalaciones_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriainstalaciones',
            name='icono',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
