# Generated by Django 5.1.2 on 2024-11-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0020_plan_categoriainstalaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadoinstalaciones',
            old_name='background_color',
            new_name='class_css',
        ),
        migrations.RemoveField(
            model_name='estadoinstalaciones',
            name='text_color',
        ),
    ]
