# Generated by Django 5.1.2 on 2024-11-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0021_rename_background_color_estadoinstalaciones_class_css_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadorecinto',
            name='class_css',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
