# Generated by Django 5.1.2 on 2024-11-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0022_estadorecinto_class_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='recinto',
            name='observacion_estado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
