# Generated by Django 5.1.2 on 2024-11-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0023_recinto_observacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pabellon',
            name='tipo_pabellon',
            field=models.IntegerField(blank=True, choices=[(1, 'Edificacción'), (2, 'Area Exterior')], default=1, null=True),
        ),
    ]
