# Generated by Django 5.1.2 on 2024-11-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0024_pabellon_tipo_pabellon'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriarecinto',
            name='boolean_area',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='categoriarecinto',
            name='boolean_pabellon',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
