# Generated by Django 5.1.2 on 2024-11-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0025_categoriarecinto_boolean_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='unidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
