# Generated by Django 5.1.2 on 2024-11-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0026_alter_partida_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
