# Generated by Django 5.1.2 on 2024-11-14 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0028_categoriapartida'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='categoria_partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='establecimiento.categoriapartida'),
        ),
    ]
