# Generated by Django 5.1.2 on 2024-11-14 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0031_tipounidad_remove_partida_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='establecimiento.tipounidad'),
            preserve_default=False,
        ),
    ]
