# Generated by Django 5.1.2 on 2024-11-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0032_partida_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipounidad',
            name='nombre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
