# Generated by Django 5.1.2 on 2024-11-22 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0033_alter_tipounidad_nombre'),
        ('mantenimiento', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida_PartidaMantencion',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.partida')),
                ('partida_mantencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.partidanomina', verbose_name='Partida Asociada (Nómina de Precios Mantención)')),
            ],
            options={
                'verbose_name': 'Partida - Partida Mantención',
                'verbose_name_plural': 'Partidas - Partidas Mantención',
            },
        ),
    ]
