# Generated by Django 5.1.2 on 2024-11-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0034_partida_partidamantencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida_partidamantencion',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
