# Generated by Django 5.1.2 on 2024-11-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0035_partida_partidamantencion_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='partida_nomina',
        ),
    ]
