# Generated by Django 5.1.2 on 2024-11-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0036_remove_partida_partida_nomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='precio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
