# Generated by Django 5.1.2 on 2024-11-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0037_alter_partida_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinfraestructura',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
