# Generated by Django 5.1.2 on 2024-12-06 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0038_planinfraestructura_fecha_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDiagnostico',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Diagnóstico Item',
                'verbose_name_plural': 'Diagnóstico Item',
            },
        ),
        migrations.CreateModel(
            name='TituloItemDiagnostico',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Diagnóstico Título Item',
                'verbose_name_plural': 'Diagnóstico Título Item',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Borrador'), (2, 'Enviado'), (3, 'Observado'), (4, 'Aprobado'), (5, 'Eliminado')], default=1)),
                ('year', models.IntegerField(default=2024)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.establecimiento')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnóstico',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico_CategoriaInstalaciones',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('categoria_instalaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.categoriainstalaciones')),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimiento.diagnostico')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.estadoinstalaciones')),
            ],
            options={
                'verbose_name': 'Diagnóstico - Instalaciones',
                'verbose_name_plural': 'Diagnóstico - Instalaciones',
            },
        ),
        migrations.CreateModel(
            name='PartidaDiagnostico',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimiento.itemdiagnostico')),
            ],
            options={
                'verbose_name': 'Diagnóstico Partida',
                'verbose_name_plural': 'Diagnóstico Partida',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico_PartidaDiagnostico',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('evaluacion', models.IntegerField(blank=True, choices=[(1, 'Sin evaluar'), (1, 'No requiere mantención'), (2, 'Requiere mantanción'), (3, 'No aplica')], default=1, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.diagnostico')),
                ('partida_diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.partidadiagnostico')),
            ],
            options={
                'verbose_name': 'Diagnóstico - Partida_Diagnóstico',
                'verbose_name_plural': 'Diagnóstico - Partida_Diagnóstico',
            },
        ),
        migrations.AddField(
            model_name='itemdiagnostico',
            name='titulo_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimiento.tituloitemdiagnostico'),
        ),
    ]
