# Generated by Django 5.1.2 on 2024-12-08 20:48

import apps.establecimiento.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0039_itemdiagnostico_tituloitemdiagnostico_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico_partidadiagnostico',
            name='evaluacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Sin evaluar'), (2, 'No requiere mantención'), (3, 'Requiere mantanción'), (4, 'No aplica')], default=1, null=True),
        ),
        migrations.CreateModel(
            name='ImagenDiagnostico',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, max_length=300, null=True, upload_to=apps.establecimiento.models.directorio_imagen_diagnostico)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.diagnostico')),
            ],
            options={
                'verbose_name': 'Diagnóstico - Imagenes',
                'verbose_name_plural': 'Diagnóstico - Imagenes',
            },
        ),
    ]
