# Generated by Django 5.1.2 on 2024-12-08 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0040_alter_diagnostico_partidadiagnostico_evaluacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagendiagnostico',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
