# Generated by Django 5.1.2 on 2024-12-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0043_diagnostico_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tituloitemdiagnostico',
            name='orden',
        ),
        migrations.AddField(
            model_name='itemdiagnostico',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
